Pausable library, actor and integration tests
Ethernal-Tech/filecoin-actor-library pull request #2
Opened 2023-03-24 09:01 UTC by milos-ethernal

- Pausable library provides basic emergency stop mechanism that can pause functionality.
- Example pausable actor that uses Pausable library.
- Integration tests.
- Updates in common integration test module.

2023-03-27 10:16 UTC, sara-ethernal requested changes

2023-03-27 15:10 UTC, milos-ethernal commented on testing/integration/tests/common/mod.rs
> +        params: params,
Changed in [this commit](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/2/commits/bafeab5eff4b212aca3032512747a216402bd0c3#diff-fe5b48fb58488645db13b3c4fc7036af3d78f62acf18b1b85b050a965ff55ae1L117)

2023-03-28 08:43 UTC, sara-ethernal approved these changes

2023-03-28 11:35 UTC, sasa-ethernal approved these changes

2023-03-31 09:51 UTC, merged