Access Control actor and integration tests
Ethernal-Tech/filecoin-actor-library pull request #5
Opened 2023-03-28 09:53 UTC by sasa-ethernal

- Access Control library provides basic implementation for role-based access control.
- Example actor that uses Access Control library.
- Integration tests.

2023-03-28 12:12 UTC, milos-ethernal requested changes

2023-03-28 12:12 UTC, milos-ethernal commented on testing/integration/tests/access_control_actor_test.rs
> +
We should test for failing of revoke role and renounce role methods, and if events are emited.

2023-03-28 12:12 UTC, milos-ethernal commented on actor_library/src/access_control/access_control.rs
> +        let empty_role_map = map::make_empty_map::<_, bool>(store).flush().context_code(
This boolean could be removed if it's not used in map

2023-03-28 12:12 UTC, milos-ethernal commented on actor_library/src/access_control/access_control.rs
> +            "AccessControl: caller cannot revoke accounts role."
```suggestion
            "AccessControl: can only renounce roles for self"
```

2023-03-29 11:24 UTC, milos-ethernal approved these changes
There's few more asserts in tests but we will fix and format with [#2](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/2) merge. Resolve now fix in reformating

2023-03-29 11:24 UTC, milos-ethernal commented on testing/integration/tests/access_control_actor_test.rs
> +    // User without USER_ROLE calls Increment
```suggestion
    // User with USER_ROLE calls Increment
```

2023-03-30 08:40 UTC, sara-ethernal commented on actor_library/src/utils/mapmap.rs
> +use crate::{make_empty_map, make_map_with_root_and_bitwidth, Keyer, Map};
Delete the file since its code is used nowhere in the project.

2023-03-30 09:51 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +}
Public trait will make all its functions public as well, so 'AccessControlPrivate' name isn't appropriate. Also, these functions are intended to be used in AccessControl actor internally and there is no need for a trait at all. I would add them as public functions in DefaultAccessControl struct, so that AccessControl actor can call them internally, but not expose them as a public trait.

2023-03-30 10:01 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +    return res.into();
```suggestion
    [role.to_be_bytes().to_vec(), account.to_bytes()].concat().into()
```

2023-03-30 10:07 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +    }
Add methods from AccessControlPrivate trait here.
```suggestion
    }

    pub fn _check_role<BS: Blockstore>(&self, store: &BS, role: Role) {
        Self::_check_role_and_account(self, store, role, DefaultAccessControl::msg_sender());
    }

    pub fn _check_role_and_account<BS: Blockstore>(&self, store: &BS, role: Role, account: Address) {
        assert_eq!(
            Self::has_role(self, store, role, account),
            true,
            "Access Control: account {} is missing role {}",
            account,
            role
        );
    }

    etc.
```

2023-03-30 10:52 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +            Some(r) => **r,
```suggestion
        match admin_roles.get(&key).unwrap() {
            Some(r) => *r,
```

2023-03-30 11:03 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn grant_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address);
Methods that can throw an error should return anyhow::Result<_>

```suggestion
    fn grant_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) -> anyhow::Result<()>;
```

2023-03-30 11:04 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn grant_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) {
```suggestion
    fn grant_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) -> anyhow::Result<()> {
```

2023-03-30 11:05 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn _grant_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) {
```suggestion
    fn _grant_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) -> anyhow::Result<()> {
```

2023-03-30 11:35 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +        }
```suggestion
    if let Err(e) = roles.set_if_absent(key, ()) {
        return Err(anyhow!(format!(
            "ERC20: failed to store new role {} for address with id: {}. Reason: {}",
            role, account.id().unwrap(), e
        )));
    }

    match roles.flush() {
        Ok(cid) => self.roles = cid,
        Err(e) => return Err(anyhow!(format!(
            "ERC20: failed to flush roles. New role {} for address with id: {}. Reason: {}",
            role, account.id().unwrap(), e
        )))
    }

    let entry = vec![Entry {
        flags: Flags::all(),
        key: String::from(ROLE_GRANTED_EVENT_KEY),
        codec: IPLD_RAW,
        value: fvm_ipld_encoding::to_vec(&RoleGrantedEvent {
            role: role,
            account: account,
            sender: Self::tx_origin(),
        })
        .unwrap()
        .into(),
    }];

    fvm_sdk::event::emit_event(&entry.into())?;
    Ok(())    
```

2023-03-30 11:44 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +            self.roles = roles.flush().unwrap();
Flush and emit_event are done only if set_if_absent returns true. That part is missing in error handling suggestion.

2023-03-30 11:48 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn renounce_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address);
Handle errors the same way as in grant_role.

```suggestion
    fn renounce_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) -> anyhow::Result<()>;
```

2023-03-30 11:52 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +                    sender: Self::tx_origin(),
```suggestion
                    sender: Self::msg_sender(),
```

2023-03-30 11:53 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +                        sender: DefaultAccessControl::tx_origin(),
```suggestion
                        sender: DefaultAccessControl::msg_sender()

2023-03-30 11:54 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +            DefaultAccessControl::tx_origin(),
```suggestion
            DefaultAccessControl::msg_sender(),
```

2023-03-30 11:55 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +    // Only called from constructor
Can also be called by actor internally.

2023-03-30 11:56 UTC, sara-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn _set_role_admin<BS: Blockstore>(&mut self, store: &BS, role: Role, admin_role: Role) {
Add error handling.

```suggestion
    fn _set_role_admin<BS: Blockstore>(&mut self, store: &BS, role: Role, admin_role: Role) -> anyhow::Result<()> {
```

2023-03-30 12:05 UTC, sara-ethernal commented on actor_library/Cargo.toml
> +fil_actors_runtime = { git = "https://github.com/filecoin-project/builtin-actors" }
fil_actors_runtime should not be used in actor_library.

2023-03-30 12:11 UTC, sara-ethernal commented on access_control_example/src/state.rs
> +    pub fn revoke_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) {
Add error handling.

2023-03-30 12:18 UTC, sara-ethernal commented on access_control_example/src/access_control_actor.rs
> +                ._set_role_admin(rt.store(), ADMIN_ROLE, ADMIN_ROLE);
Add set_role_admin function to state.rs and handle errors the same way as in grant_role.

2023-03-30 12:19 UTC, sara-ethernal commented on access_control_example/src/access_control_actor.rs
> +            st.renounce_role(rt.store(), params.role, params.account);
```suggestion
            st.renounce_role(rt.store(), params.role, params.account)?;
```

2023-03-31 08:17 UTC, sasa-ethernal commented on testing/integration/tests/access_control_actor_test.rs
> +    assert_eq!(role_granted, true);
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/bd7fd354f1455aea5402a51633629c360b49f455#diff-dcbb66c6f17eabadd5c7877056c70eb713b9a9d2a2534046fab04a7e7b42ab0fL129)

2023-03-31 08:18 UTC, sasa-ethernal commented on testing/integration/tests/access_control_actor_test.rs
> +    // let params = RoleAccount{role: USER_ROLE, account: Address::new_id(user_id)};
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/bd7fd354f1455aea5402a51633629c360b49f455#diff-dcbb66c6f17eabadd5c7877056c70eb713b9a9d2a2534046fab04a7e7b42ab0fL207)

2023-03-31 08:23 UTC, sasa-ethernal commented on testing/integration/tests/access_control_actor_test.rs
> +
Added more tests:
- Revoke role failed: [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/bd7fd354f1455aea5402a51633629c360b49f455#diff-dcbb66c6f17eabadd5c7877056c70eb713b9a9d2a2534046fab04a7e7b42ab0fR279)
- Renounce role failed: [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/bd7fd354f1455aea5402a51633629c360b49f455#diff-dcbb66c6f17eabadd5c7877056c70eb713b9a9d2a2534046fab04a7e7b42ab0fR427)
- Events emitted: [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/bd7fd354f1455aea5402a51633629c360b49f455#diff-dcbb66c6f17eabadd5c7877056c70eb713b9a9d2a2534046fab04a7e7b42ab0fR672)

2023-03-31 08:24 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +        let empty_role_map = map::make_empty_map::<_, bool>(store).flush().context_code(
Replaced boolean value with empty value [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/bd7fd354f1455aea5402a51633629c360b49f455#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R72)

2023-03-31 08:24 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +            "AccessControl: caller cannot revoke accounts role."
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/bd7fd354f1455aea5402a51633629c360b49f455#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R136)

2023-03-31 08:26 UTC, sasa-ethernal commented on actor_library/src/utils/mapmap.rs
> +use crate::{make_empty_map, make_map_with_root_and_bitwidth, Keyer, Map};
Removed [mapmap](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-1ae4adb84020e8abbe92175a82b330fe1d9434b0fc367136d4009bf4ddd59e2a) since it's not being used

2023-03-31 08:29 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +}
AccessControlPrivate trait [removed](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0L58) and all methods are moved to [impl](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R103)

2023-03-31 08:30 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    return res.into();
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R263)

2023-03-31 08:31 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    }
Methods added [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R103)

2023-03-31 08:33 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    pub fn new<BS: Blockstore>(store: &BS) -> Result<Self, ActorError> {
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R71)

2023-03-31 08:34 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +            Some(r) => **r,
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R234)

2023-03-31 08:34 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn grant_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address);
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R239)

2023-03-31 08:34 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn grant_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) {
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R239)

2023-03-31 08:38 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn _grant_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) {
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R144)

2023-03-31 08:39 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +        }
Fixed according to example and clippy suggestions [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R148)

2023-03-31 08:42 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn revoke_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address);
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-f4f5070218d13652123ba81cda4da327b8e6405ab033ecce7479cf58d8666e89R60)

2023-03-31 08:43 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn renounce_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address);
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-f4f5070218d13652123ba81cda4da327b8e6405ab033ecce7479cf58d8666e89R67)

2023-03-31 08:44 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +                    sender: Self::tx_origin(),
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R174)

2023-03-31 08:45 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +                        sender: DefaultAccessControl::tx_origin(),
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R204)

2023-03-31 08:46 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +            DefaultAccessControl::tx_origin(),
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R253)

2023-03-31 08:46 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    // Only called from constructor
Changed [comment](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R102)

2023-03-31 08:47 UTC, sasa-ethernal commented on actor_library/src/access_control/access_control.rs
> +    fn _set_role_admin<BS: Blockstore>(&mut self, store: &BS, role: Role, admin_role: Role) {
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-324b0e57c0074407a39059591d361b952bc9f0f06b445d4376767d222ba55ef0R103)

2023-03-31 08:47 UTC, sasa-ethernal commented on actor_library/Cargo.toml
> +fil_actors_runtime = { git = "https://github.com/filecoin-project/builtin-actors" }
Removed fil_actors_runtime [dependency](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-c1ccf48b5e8b512fdcf8d90605b7fe01be0eb94fadac60194d14581d75ade18dL9)

2023-03-31 08:48 UTC, sasa-ethernal commented on access_control_example/src/state.rs
> +    }
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-f4f5070218d13652123ba81cda4da327b8e6405ab033ecce7479cf58d8666e89R54)

2023-03-31 08:49 UTC, sasa-ethernal commented on access_control_example/src/state.rs
> +    pub fn revoke_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) {
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-f4f5070218d13652123ba81cda4da327b8e6405ab033ecce7479cf58d8666e89R61)

2023-03-31 08:49 UTC, sasa-ethernal commented on access_control_example/src/state.rs
> +    pub fn renounce_role<BS: Blockstore>(&mut self, store: &BS, role: Role, account: Address) {
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-f4f5070218d13652123ba81cda4da327b8e6405ab033ecce7479cf58d8666e89R68)

2023-03-31 08:50 UTC, sasa-ethernal commented on access_control_example/src/access_control_actor.rs
> +                ._set_role_admin(rt.store(), ADMIN_ROLE, ADMIN_ROLE);
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-f4f5070218d13652123ba81cda4da327b8e6405ab033ecce7479cf58d8666e89R46)

2023-03-31 08:51 UTC, sara-ethernal commented on actor_library/src/access/access_control.rs
> +        self.roles = cid;
```suggestion
        self.roles = roles.flush().map_err(|e| {
            anyhow!(format!(
                "AccessControl: failed to flush roles. New role {} for address with id: {}. Reason: {}",
                role, account.id().unwrap(), e
            ))
        })?;
```

2023-03-31 08:51 UTC, sasa-ethernal commented on access_control_example/src/access_control_actor.rs
> +            st.grant_role(rt.store(), params.role, params.account);
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-d8338c65fb8981fdd73a31728b9cf833fd687ff061bd2c1afdfc5e1dacd4761dR145)

2023-03-31 08:51 UTC, sasa-ethernal commented on access_control_example/src/access_control_actor.rs
> +            st.revoke_role(rt.store(), params.role, params.account);
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-d8338c65fb8981fdd73a31728b9cf833fd687ff061bd2c1afdfc5e1dacd4761dR156)

2023-03-31 08:52 UTC, sasa-ethernal commented on access_control_example/src/access_control_actor.rs
> +            st.renounce_role(rt.store(), params.role, params.account);
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/dcd00ad0e72ae3cb2412881b9b4a8a415dcf9860#diff-d8338c65fb8981fdd73a31728b9cf833fd687ff061bd2c1afdfc5e1dacd4761dR167)

2023-03-31 08:52 UTC, sara-ethernal commented on actor_library/src/access/access_control.rs
> +            fvm_sdk::event::emit_event(&entry.into()).unwrap();
```suggestion
            fvm_sdk::event::emit_event(&entry.into())?;
```

2023-03-31 09:47 UTC, sasa-ethernal commented on actor_library/src/access/access_control.rs
> +        self.roles = cid;
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/65cfd2c37c4801b3cb3f7137117645b798ca590b#diff-4a38a1824577f86dd75206445434541fc3349a3400d1793facc0fb3c34f5b2beR182)

2023-03-31 09:48 UTC, sasa-ethernal commented on actor_library/src/access/access_control.rs
> +            self.roles = roles.flush().unwrap();
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/65cfd2c37c4801b3cb3f7137117645b798ca590b#diff-4a38a1824577f86dd75206445434541fc3349a3400d1793facc0fb3c34f5b2beR225)

2023-03-31 09:48 UTC, sasa-ethernal commented on actor_library/src/access/access_control.rs
> +            fvm_sdk::event::emit_event(&entry.into()).unwrap();
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/65cfd2c37c4801b3cb3f7137117645b798ca590b#diff-4a38a1824577f86dd75206445434541fc3349a3400d1793facc0fb3c34f5b2beR244)

2023-03-31 09:48 UTC, sasa-ethernal commented on actor_library/src/access/access_control.rs
> +        self.admin_roles = cid;
FIxed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/65cfd2c37c4801b3cb3f7137117645b798ca590b#diff-4a38a1824577f86dd75206445434541fc3349a3400d1793facc0fb3c34f5b2beR136)

2023-03-31 09:49 UTC, sasa-ethernal commented on actor_library/src/access/access_control.rs
> +        fvm_sdk::event::emit_event(&entry.into()).unwrap();
Fixed [here](https://github.com/Ethernal-Tech/filecoin-actor-library/pull/5/commits/65cfd2c37c4801b3cb3f7137117645b798ca590b#diff-4a38a1824577f86dd75206445434541fc3349a3400d1793facc0fb3c34f5b2beR155)

2023-03-31 09:49 UTC, sara-ethernal approved these changes

2023-03-31 10:32 UTC, merged